# Generated by Django 3.2.5 on 2022-01-20 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('album_image', models.ImageField(blank=True, upload_to='', verbose_name='Media/Music/Albums')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded', models.DateTimeField(auto_created=True)),
                ('song_name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='Media/Music/Songs')),
                ('slug', models.SlugField(unique=True)),
                ('song_length', models.TimeField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_songs', to='Music.album')),
            ],
            options={
                'ordering': ['-uploaded'],
            },
        ),
    ]
