# Generated by Django 3.2.5 on 2022-01-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0003_alter_song_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_image',
            field=models.ImageField(upload_to='', verbose_name='Media/Music/Albums'),
        ),
    ]
