# Generated by Django 3.2.5 on 2022-01-24 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Music', '0005_auto_20220120_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_albums', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='uploaded',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
