# Generated by Django 3.2.5 on 2022-01-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0006_auto_20220124_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_length',
            field=models.TimeField(default='1:20:20'),
        ),
    ]
