# Generated by Django 3.2.5 on 2022-01-26 14:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Music', '0008_song_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audience',
            field=models.ManyToManyField(blank=True, related_name='user_collections', to=settings.AUTH_USER_MODEL),
        ),
    ]
