# Generated by Django 3.2.11 on 2022-01-31 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0010_song_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailsApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
