# Generated by Django 3.2.11 on 2022-01-31 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Music', '0011_emailsapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='users_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='album_songs', to='Music.album'),
        ),
    ]
